version: '2'

services:
  app:
    build: .
    container_name: kalikesia
    environment:
      - FLASK_APP=manage.py
      - FLASK_DEBUG=True
      - APP_SETTINGS=config.DevelopmentConfig
      - SECRET_KEY=secret-key
      - DATABASE_URL=sqlite:///db.sqlite
      - MAIL_USERNAME=noreply@domain.com
      - MAIL_PASSWORD=mailpass
    command: python -m flask run --host 0.0.0.0 --port 5000
    ports:
      - '5000:5000'
    volumes:
      - .:/var/www/kalikesia
