# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 5000, host: 5000, auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 8081, auto_correct: true
  config.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: "vboxnet0"

  config.vm.synced_folder "/", "/vagrant"

  # VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Kalikesia" # friendly name that shows up in Oracle VM VirtualBox Manager
    vb.memory = 1024 # memory in megabytes
    vb.cpus = 4 # cpu cores, can't be more than the host actually has!
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"] # fixes slow dns lookups
  end


  config.vm.provision :shell, path: "vagrant.sh"
  # enable logging in via ssh with a password
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

end
